### ISSUE TITLE
Update to Technitium version 10.0.1

### ISSUE THREAD

**Issue by renne** [YunoHost-Apps/technitium-dns_ynh#5]
### Describe the bug

Please update this app to Technitium version 10.0.1

### Context

- Hardware: Proxmox KVM on bare metal
- YunoHost version: 11.0.11
- I have access to my server: Through SSH | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 8.1.4~ynh2

### Steps to reproduce

Install this app.

### Expected behavior

Technitium version 10.0.1

**Comment by renne** [comment]
@navanchauhan 
@yalh76 
Are there any plans for the update?

**Comment by yalh76** [comment]
no plan for me but feel free to do a PR ;)

**Comment by navanchauhan** [comment]
As soon as I get my YunoHost server setup again, I will be pushing an update. A week or two at max

**Comment by renne** [comment]
@navanchauhan 
Current Technitium version is 11.3

**Comment by yalh76** [comment]
> @navanchauhan Current Technitium version is 11.3

Feel free to do a PR

**Comment by navanchauhan** [comment]
@renne please test the testing branch once I merge #7 

I do not have a functional local YunoHost setup right now to test it manually

**Comment by renne** [comment]
@navanchauhan 
The Yunohost app installed fine and at first glance the web-interface is working fine, too.
I'll test the functionality in the next days. :-)

**Comment by renne** [comment]
@navanchauhan 
Currently there are two problems:

- Dnsmasq blocks port 53
- Technitium lacks the permission to bind to port 53 even if Dnsmasq is stopped and port 53 is unused.

```
$:/etc# netstat -tulpn | grep -i :53
tcp6       0      0 :::5380                 :::*                    LISTEN      45899/dotnet        
udp        0      0 192.168.1.11:5353       0.0.0.0:*                           584/python3         
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           584/python3

```
```
[2023-08-01 16:43:52 UTC] [0.0.0.0:53] [UDP] DNS Server failed to bind.

System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DnsServerCore.Dns.DnsServer.StartAsync() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 4006
[2023-08-01 16:43:52 UTC] [0.0.0.0:53] [TCP] DNS Server failed to bind.

System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DnsServerCore.Dns.DnsServer.StartAsync() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 4025
[2023-08-01 16:43:52 UTC] [[::]:53] [UDP] DNS Server failed to bind.

System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DnsServerCore.Dns.DnsServer.StartAsync() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 4006
[2023-08-01 16:43:52 UTC] [[::]:53] [TCP] DNS Server failed to bind.

System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DnsServerCore.Dns.DnsServer.StartAsync() in Z:\Technitium\Projects\DnsServer\DnsServerCore\Dns\DnsServer.cs:line 4025
```

**Comment by navanchauhan** [comment]
This must be a systemd hardening issue for #2.

The reason I did not advertise this app on the forum is because it cannot coexist with Dnsmasq, so I will let the step of disabling Dnsmasq be a manual option (but I will update the docs with instructions regarding the same)
